import = ["/home/goose/.config/alacritty/theme.toml"]

[cursor]
blink_interval = 750

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 9

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_padding = false

[window.padding]
x = 7
y = 7
